; Se debe crear un archivo de configuración llamado configuracion.ini en la carpeta backend/App/config con la siguiente estructura:

[database]
SERVIDOR             = 3.131.40.57
PUERTO               = 1521
USUARIO              = ESIACOM
PASSWORD             = ESIACOM

[otros]
URL_HUELLAS          = 
URL_CDC              = 


[acceso]
HERRAMIENTAS_CLAVE   =