; Se debe crear un archivo de configuración llamado configuracion.ini en la carpeta backend/App/config con la siguiente estructura:

[database]
SERVIDOR             = 
PUERTO               = 
USUARIO              = 
PASSWORD             = 
ESQUEMA              =

[otros]
URL_HUELLAS          = 
URL_CDC              = 


[acceso]
HERRAMIENTAS_CLAVE   =